settings:
  username: "radmanesh" # Replace with your username or comment out this line
  commit_msg: "Update README with the recent activity"
  readme_file: "./README.md"
  date:
    text: "Last Updated: {DATE} (GMT)"
